### ISSUE TITLE
removed from CRAN?

### ISSUE THREAD

**Issue by mkoohafkan** [dbdahl/cargo-framework#2]
The [cargo CRAN page](https://cran.r-project.org/web/packages/cargo/index.html) states:

> Package ‘cargo’ was removed from the CRAN repository.
Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/cargo).
Archived on 2022-07-21 as fails to detect system installation of 'cargo', and does not report failure when 'cargo' is not found.

Are there any plans to republish on CRAN?

**Comment by dbdahl** [comment]
Yes, I submitted an update to CRAN on 2022-09-28. I sent a follow-up email on 2022-10-17. I have not heard back yet, but I am still committed to getting it back on CRAN.

**Comment by dbdahl** [comment]
The package is back on CRAN. https://cran.r-project.org/web/packages/cargo/index.html
