### ISSUE TITLE
Link to "Writing R Extensions in Rust" broken

### ISSUE THREAD

**Issue by JohannesFriedrich** [dbdahl/cargo-framework#3]
The link to your paper "Writing R Extensions in Rust" mentioned in the Readme is broken:

https://raw.githubusercontent.com/dbdahl/cargo-framework/main/cargo/inst/doc/Writing_R_Extensions_in_Rust.pdf

**Comment by dbdahl** [comment]
Thanks for the report.  It's working again.

**Comment by JohannesFriedrich** [comment]
Thanks, so I close this issue.
